### ISSUE TITLE
Juce 5 / Projucer - build error file not found

### ISSUE THREAD

**Issue by DerGroncki** [WeAreROLI/JUCE#185]
I created a new GUI application (with Projucer) on Windows 10 Pro with VS2017 installed.

If I build the project inside Projucer I get some errors:
error: C:\Users\micha\Documents\Visual Studio 2017\Projects\MyFirstJuce\Source\MainComponent.cpp: 'memory' file not found
error: C:\Users\micha\Documents\Visual Studio 2017\Projects\MyFirstJuce\JuceLibraryCode\include_juce_audio_devices.cpp: 'excpt.h' file not found

Any recommendation how to fix this (I can’t find a path setting or something like this).

Thank you.
Michael

**Comment by ed95** [comment]
Thanks for the report. This is now fixed in the 5.0.1 release.

**Comment by kybr** [comment]
I'm using Projucer 5.0.1 on Windows 10 with Visual Studio Community and I still get these same errors.

**Comment by SeedyROM** [comment]
Still not fixed getting, this is more than half a year later.

**Comment by ed95** [comment]
Those files should be located in the `Program Files (x86)\Windows Kits\10\` directory. By default the live-build engine looks for these under the 10.0.16299.0 subfolder but if you have a different version of the Windows 10 SDK installed then you’ll need to set this in ‘Windows Target Platform’ section of the live-build settings:

<img width="773" alt="screen shot 2018-02-07 at 09 46 08" src="https://user-images.githubusercontent.com/6862971/35909531-da48a1b4-0beb-11e8-859d-f97ee50df600.png">
