### ISSUE TITLE
[Android] DemoRunner fails with "Error while Launching Activity"

### ISSUE THREAD

**Issue by dturner** [WeAreROLI/JUCE#439]
JUCE 5.4.1 (master branch)
Pixel XL running Pie

Steps to repro: 

- Open DemoRunner project in Projucer
- Select Android target and open in Android Studio (3.2.1)
- Hit Run

Expected result: 

- DemoRunner app runs as expected

Actual result: 

- DemoRunner app does not run and the following errors are displayed in the "Run" tab in Android Studio: 

11/14 16:06:37: Launching app
$ adb shell am start -n "com.juce.demorunner/android.app.Activity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "com.juce.demorunner/android.app.Activity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.juce.demorunner/android.app.Activity }
Error type 3
Error: Activity class {com.juce.demorunner/android.app.Activity} does not exist.

Error while Launching activity

**Comment by dturner** [comment]
This was being caused by an outdated version of gradle. Fixed in https://github.com/WeAreROLI/JUCE/pull/436

**Comment by lukaszkozakiewicz-roli** [comment]
https://github.com/WeAreROLI/JUCE/pull/436 is now merged to develop. Does the issue still persist on the latest develop?

**Comment by dturner** [comment]
Issue fixed on develop - thanks.
