### ISSUE TITLE
getRawParameterValue does not provide correct value in parameterValueChanged

### ISSUE THREAD

**Issue by arikauppi** [WeAreROLI/JUCE#453]
With the latest updates, it seems that getRawParameterValue does not anymore provide the updated value in parameterValueChanged. This used to be the behavior in JUCE 5.3.2 but not anymore with JUCE 5.4.1.

Short minimized pseudo-code from the problem:

// Setup
juce::AudioProcessorValueTreeState parameters;

parameters.createAndAddParameter(std::make_unique<AudioParameterFloat>(angleStr, angleStr, -juce::MathConstants<float>::pi, juce::MathConstants<float>::pi, 0.f));

// Update param
parameters.getParameter(angleStr)->setValueNotifyingHost(1.f);

// Listener class
parameters->getParameter(angleStr)->addListener(this);

parameterValueChanged(int /*parameterIndex*/, float /*newValue*/) {
  // provides old value in JUCE 5.4.1, new value in 5.3.2
  float angle = *parameters.getRawParameterValue(angleStr);
  // provides old value in JUCE 5.4.1
  float angle2 = (float)parameters.getParameterAsValue(angleStr).getValue();
  // provides new value in JUCE 5.4.1
  float angle3 = (float)parameters.getParameter(angleStr)->getNormalisableRange().convertFrom0to1(parameters.getParameter(angleStr)->getValue());
  // provides new value in JUCE 5.4.1
  String angle4 = parameters.getParameter(angleStr)->getCurrentValueAsText();
}

This seems to happen due to the fact that the AudioProcessorValueTreeState::ParameterAdapter listener to update the unnormalisedValue is called after the user added listener for handling the parameterValueChanged.

ParameterAdapter listener is added during parameter creation and AudioProcessorParameter::sendValueChangedMessageToListeners calls listeners in reverse order -> AudioProcessorValueTreeState::ParameterAdapter is called last, after the user registered listeners.

I would expect that the four different methods to get the unnormalised value would provide the same result.

**Comment by McMartin** [comment]
This issue might have been fixed on the `develop` branch in this commit: https://github.com/WeAreROLI/JUCE/commit/167a3a86b1b5c715ff8b981a5ba34187cdbb1757

**Comment by arikauppi** [comment]
This issue seems to be still present with develop@31025ae3e6557109fb08113b2a2856a969dea927.

**Comment by arikauppi** [comment]
Uglyish test case to reproduce the issue with develop@31025ae3e6557109fb08113b2a2856a969dea927

[0001-Add-test-case-for-getRawParameterValue-in-AudioProce.patch.txt](https://github.com/WeAreROLI/JUCE/files/2683860/0001-Add-test-case-for-getRawParameterValue-in-AudioProce.patch.txt)

**Comment by ed95** [comment]
Thanks for raising this issue and providing a test case to reproduce. You're right that the order of listeners is the reason for the `getRawParameterValue()` method not returning the latest value from within the listener callback. The `getParameterAsValue()` method is returning an old value because at the point of the callback happening the new value has not been flushed to the ValueTree as this is happening on a timer for performance reasons.

I think it's a bit of a strange edge case though - why would you need to query the parameter value from within the listener callback when you are provided the up-to-date value as a function parameter? I'm hesitant to create a workaround unless there is a specific reason that you need to do this? Instead I think it's best to update the documentation of the relevant methods to indicate that querying the parameter values from within the listener callback will not return the latest value and that only the `newValue` parameter should be relied upon. I've pushed this in [548838e](https://github.com/WeAreROLI/JUCE/commit/548838e13996d53e3c36420cb3465cfbf800da9d).

**Comment by arikauppi** [comment]
This was originally due to generic non-JUCE engine code being called from parameter listener which then eventually queried for parameter value via some JUCE wrappers.

After finding the root cause I already refactored the code to avoid parameter extra lookups. I think documenting the fact is fine.
